---
title: "Publications"
---

### Peer Reviewed Journals

8. Rosenberg EJ^, Bradley D, Gaines SD, **Caughman AM**. Marine fish trait interactions create specific contexts where different ontogenetic movement combinations arise. Marine Ecology Progress Series. Accepted ^undergraduate
7. Feitosa LM^, **Caughman AM^**, D’Costa N, Orofino S, Burns ES, Schiller L, Worm B, Bradley D. 2025. Retention prohibitions are likely insufficient to recover overfished shark populations. Fish and Fisheries. 0:1–15 ^co-first authors
6. Cabral RB, Millage KD, Mayorga J, Kordell T, Kelkar M, **Caughman AM**, Favoretto F, Schuhbauer A, Aburto-Oropeza O, Sala E, Bradley D. 2025. A global network of marine protected areas for dive tourism. Sci Rep. 15:1923
5. Bradley D^, **Caughman AM^**, Fogg S, Cabral RB, Mayorga J, Goodell W, Millage KD, White TD. 2024. Marine Fish Movement: home range sizes for commercially relevant species. Sci Data 11, 865 *co-first authors ^co-first authors
4. **Caughman AM**, Gaines SD, Bradley D. 2024. Climate change reduces population benefits from marine protected areas through selective pressures on species movement. Global Change Biology. 30(3), e17240.
3. **Caughman AM**, Weigel EG. 2022. Biology students’ math and computer science task values are closely linked. CBE – Life Sciences Education. 21(3):ar43.
2.	**Caughman AM^**, Pratte ZA^, Patin NV, Stewart FJ. 2021. Coral microbiome changes over the day-night cycle. Coral Reefs. 40(3)921-935. ^co-first authors
1.	Pratte ZA, Patin NV, McWhirt ME, **Caughman AM**, Parris DJ, Stewart FJ. 2018. Association with a sea anemone alters the skin microbiome of clownfish. Coral Reefs. 37(4):1119-1125.


### In Review


### In Prep

2. **Caughman AM**, Caselle JE, Gaines SD, Bradley D. Adult movement drives connectivity patterns and population sizes more than larval dispersal in marine protected areas. Submitted to PNAS
1. **Caughman AM**, Yanco S, Easterday K, Gao S, Hiroyasu E, Rutz C, Oliver RY. Supporting biodiversity and human use of California's protected area. For Submission to Frontiers in Ecology and the Environment

### Other Publications and Creative Products
 
4. Bradley D^, **Caughman A^**, Fogg S, Cabral RB, Mayorga J, Goodell W, Millage KD, White TD. 2024. Marine Fish Movement [Dataset]. Dryad. https://doi.org/10.25349/D96C9M ^co-first authors
3.	**Caughman, A**., Alexander, K., Munster, K. 2022. Visualizing Commercially Relevant Fish Home Range Sizes. https://emlab-ucsb.shinyapps.io/fish_homeranges/
2.	**Caughman A**., Weigel EG. 2021. Investigating human impacts on Southeastern US stream ecology using R. QUBES Educational Resources. doi:10.25334/P995-7G91
1.	**Caughman AM**. 2020. Variation in Coral Microbiome Composition and Transcriptional Activity of Three Corals over Diel Cycles [bachelor’s thesis]. Georgia Institute of Technology

