---
title: "Teaching"
---

I am passionate about making computational and statistical skills more accessible to students in ecology and environmental science. I was lucky to attend a school (Georgia Tech) where coding and statistics were both a requirement in my biology major, but still I saw my of my peers avoiding and dreading the requirement, despite how useful such skills are, and most biology classes were still using older technology for data analysis, such as minitab. As someone who both loves and values her statistical and coding skills, I've made it a mission to imbue students with the excitement and utility of these tools and reduce barriers to learning them. As part of my PhD, I am completing the CCUT (Certificate in College and University Teaching) in order to enhance my skills as a teacher and learn evidence-based strategies to accomplish my teaching goals.

### Instructor of Record

University of California Santa Barbara

* Summer 2024: INT 93LS Introduction to Research in STEM, Humanities, and Social Sciences - Data Science and Marine Ecology

### Teaching Assistant 

University of California Santa Barbara

* Fall 2023: EDS 223 Geospatial Analysis and Remote Sensing 
* Winter 2024: EDS 232 Machine Learning in Environmental Science
* Spring 2024: EDS 411B Capstone Seminar

Georgia Institute of Technology

* Fall 2018: BIOL 1510 Biological Principles Lab 
* Fall 2018: COS 2000 Introduction to Research
* Spring 2019: BIOL 1520 Introduction to Organismal Biology Recitation

### Resource Development 

* I developed a Swirl Module in R for BIOS 2301, the Ecology Lab at Georgia Tech that walks students through analyzing stream health data from the EPA for streams across the United States using descriptive statistics and linear regression. 
* I developed the curriculum for a 4-week special topics and research seminar geared towards teaching students marine ecology, statistics, and coding in R and culminated in a group research project demonstrating what they learned. 
